apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-vue-sso
  namespace: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-vue-sso
      namespace: vue-app
  template:
    metadata:

    spec:
      containers:
        - name: demo-vue-sso
          image: 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SSO_ENDPOINT
              valueFrom:
                configMapKeyRef: demo-vue-sso-cm
                key: sso.endpoint
            - name: SSO_REALM
              valueFrom:
                configMapKeyRef: demo-vue-sso-cm
                key: sso.realm
            - name: SSO_CLIENTID
              valueFrom:
                configMapKeyRef: demo-vue-sso-cm
                key: sso.clientid